export const car = {
  "chapter-01": [
    {
      type: "dialogue",
      text: "«سلام کوچولوهای کنجکاو! جایی توی دل دشت‌ها، شهری هست که بهش می‌گن لاله؛ شهری آرام و سبز که شاید خیلی بزرگ نباشه.»",
      charecter: "ravi",

      typeSpeed: 26,
      textColor: "#ffffff",
      bgColor: "#0b3b4a",
      bgImage: "/scenes/car/chapters/1.png",
      fontSize: 14,
      meta: null,
    },
    {
      type: "dialogue",
      text: "«اما توی دلش کلی رویای بزرگ جا شده. بچه‌های این شهر زیاد نیستند، ولی دل‌هاشون اندازهٔ کوه بزرگه!»",
      charecter: "ravi",

      typeSpeed: 26,
      textColor: "#ffffff",
      bgColor: "#0b3b4a",
      bgImage: "/scenes/car/chapters/1.png",
      fontSize: 14,
      meta: null,
    },
    {
      type: "dialogue",
      text: "«امروز می‌خوایم با سه تا قهرمان پرانرژی آشنا بشیم؛ سه پسری که تصمیم گرفتن مسئله‌ها را به پروژه تبدیل کنند.»",
      charecter: "ravi",

      typeSpeed: 26,
      textColor: "#ffffff",
      bgColor: "#0b3b4a",
      bgImage: "/scenes/car/chapters/1.png",
      fontSize: 14,
      meta: null,
    },
    {
      type: "dialogue",
      text: "«سلام! من آرشم. همیشه دوست دارم بدونم؛ مدام می‌پرسم چرا و چطور. چند بار امتحان می‌کنم تا مطمئن بشم همه‌چی درست کار می‌کنه. رنگ مورد علاقه‌ام بنفشه!»",
      charecter: "arash",
      mode: "1",
      typeSpeed: 30,
      textColor: "#ffffff",
      bgColor: "#7c3aed",
      bgImage: "/scenes/car/chapters/2.png",
      fontSize: 15,
      meta: null,
    },
    {
      type: "dialogue",
      text: "«هی رفقا! من سینام. از حرف زدن با آدما و دوست شدن باهاشون کیف می‌کنم. رنگ محبوبم زرده؛ مثل خورشید پرانرژی!»",
      charecter: "sina",
      mode: "1",
      typeSpeed: 30,
      textColor: "#000000",
      bgColor: "#fef3c7",
      bgImage: "/scenes/car/chapters/2.png",
      fontSize: 15,
      meta: null,
    },
    {
      type: "dialogue",
      text: "«درود! من محمدم. اهل حساب‌وکتابم و دوست دارم همه‌چیز برام روشن و مرتب باشه. رنگ مورد علاقه‌ام آبی آسمونی و عاشق قورمه‌سبزیم!»",
      charecter: "mohammad",
      mode: "1",
      typeSpeed: 30,
      textColor: "#000000",
      bgColor: "#e0f2fe",
      bgImage: "/scenes/car/chapters/2.png",
      fontSize: 15,
      meta: null,
    },
    {
      type: "dialogue",
      text: "«بچه‌ها، اگه بزرگ شدیم، دوست دارید چی‌کاره بشید؟ من یه عالمه گزینه تو ذهنمه.»",
      charecter: "arash",
      mode: "4",
      typeSpeed: 26,
      textColor: "#ffffff",
      bgColor: "#7c3aed",
      bgImage: "/scenes/car/chapters/3.png",
      fontSize: 15,
      meta: null,
    },
    {
      type: "dialogue",
      text: "«خیلی دوست دارم هر وسیله‌ای رو باز کنم ببینم چطور کار می‌کنه؛ شاید مهندس مکانیک بشم.»",
      charecter: "sina",
      mode: "3",
      typeSpeed: 26,
      textColor: "#000000",
      bgColor: "#fef3c7",
      bgImage: "/scenes/car/chapters/3.png",
      fontSize: 15,
      meta: null,
    },
    {
      type: "dialogue",
      text: "«من عاشق دنیای الکترونیکم؛ سیم‌ها، باتری‌ها و ربات‌ها... می‌خوام مهندس الکترونیک بشم.»",
      charecter: "mohammad",
      mode: "2",
      typeSpeed: 26,
      textColor: "#000000",
      bgColor: "#e0f2fe",
      bgImage: "/scenes/car/chapters/3.png",
      fontSize: 15,
      meta: null,
    },
    {
      type: "dialogue",
      text: "«من هم عاشق کدنویسی و بازی‌سازی‌ام؛ دوست دارم مغز ربات‌ها رو طراحی کنم.»",
      charecter: "arash",
      mode: "5",
      typeSpeed: 26,
      textColor: "#ffffff",
      bgColor: "#7c3aed",
      bgImage: "/scenes/car/chapters/3.png",
      fontSize: 15,
      meta: null,
    },
    {
      type: "dialogue",
      text: "«بیایید دانشمند بشیم؛ کسی که سؤال می‌پرسه، آزمایش می‌کنه و چیز جدید اختراع می‌کنه.»",
      charecter: "arash",
      mode: "3",
      typeSpeed: 26,
      textColor: "#ffffff",
      bgColor: "#7c3aed",
      bgImage: "/scenes/car/chapters/3.png",
      fontSize: 15,
      meta: null,
    },
    {
      type: "dialogue",
      text: "«هر شغل مفید می‌تونه به آدم‌ها کمک کنه؛ مهم اینه مسئله‌ای رو حل کنیم.»",
      charecter: "sina",
      mode: "2",
      typeSpeed: 26,
      textColor: "#000000",
      bgColor: "#fef3c7",
      bgImage: "/scenes/car/chapters/3.png",
      fontSize: 14,
      meta: null,
    },
    {
      type: "dialogue",
      text: "«پس اول باید مسئله پیدا کنیم؛ یک مشکل واقعی توی خونه‌هامون.»",
      charecter: "mohammad",
      mode: "2",
      typeSpeed: 26,
      textColor: "#000000",
      bgColor: "#e0f2fe",
      bgImage: "/scenes/car/chapters/4.png",
      fontSize: 14,
      meta: null,
    },
    {
      type: "dialogue",
      text: "«وقتی دارم بازی می‌کنم، اسباب‌بازی‌های کوچیک یا پیچ‌ها می‌افتن روی زمین؛ جمع‌کردنشون برام سخته.»",
      charecter: "sina",
      mode: "2",
      typeSpeed: 26,
      textColor: "#000000",
      bgColor: "#fef3c7",
      bgImage: "/scenes/car/chapters/4.png",
      fontSize: 15,
      meta: null,
    },
    {
      type: "dialogue",
      text: "«توی اتاقم موقع جابه‌جایی وسایل زود خسته می‌شم؛ دوست دارم چیزی کمکم کنه بدون خستگی جابه‌جا کنم.»",
      charecter: "mohammad",
      mode: "2",
      typeSpeed: 26,
      textColor: "#000000",
      bgColor: "#e0f2fe",
      bgImage: "/scenes/car/chapters/4.png",
      fontSize: 15,
      meta: null,
    },
    {
      type: "dialogue",
      text: "«من می‌خوام یک زمین بسکتبال کوچیک توی اتاقم بسازم و توپ‌ها رو توی سبد بندازم.»",
      charecter: "arash",
      mode: "3",
      typeSpeed: 26,
      textColor: "#ffffff",
      bgColor: "#7c3aed",
      bgImage: "/scenes/car/chapters/4.png",
      fontSize: 15,
      meta: null,
    },
    {
      type: "dialogue",
      text: "«وسایل اتاق وقتی شلوغ می‌شن، مرتب‌کردنشون سخته؛ کاش یک چیزی جابه‌جاشون کنه و سر جاشون بذاره.»",
      charecter: "sina",
      mode: "3",
      typeSpeed: 26,
      textColor: "#000000",
      bgColor: "#fef3c7",
      bgImage: "/scenes/car/chapters/4.png",
      fontSize: 15,
      meta: null,
    },
    {
      type: "dialogue",
      text: "«گاهی باید جامدادی یا جعبه‌های کوچیک رو از این‌طرف اتاق به اون‌طرف ببریم، بدون اینکه با دست بلندش کنیم. چی بسازیم؟»",
      charecter: "ravi",

      typeSpeed: 26,
      textColor: "#ffffff",
      bgColor: "#0b3b4a",
      bgImage: "/scenes/car/chapters/4.png",
      fontSize: 14,
      meta: null,
    },
    {
      type: "dialogue",
      text: "«بیایید یک ماشین کنترلی بسازیم که یدک‌کش داشته باشه و وسایل سبک رو بکشه.»",
      charecter: "sina",
      mode: "3",
      typeSpeed: 26,
      textColor: "#000000",
      bgColor: "#fef3c7",
      bgImage: "/scenes/car/chapters/5.png",
      fontSize: 15,
      meta: null,
    },
    {
      type: "dialogue",
      text: "«من کدنویسی و کنترل از داخل اپ رو انجام می‌دم.»",
      charecter: "arash",
      mode: "5",
      typeSpeed: 26,
      textColor: "#ffffff",
      bgColor: "#7c3aed",
      bgImage: "/scenes/car/chapters/5.png",
      fontSize: 15,
      meta: null,
    },
    {
      type: "dialogue",
      text: "«من مدار و باتری رو طوری می‌سازم که ایمن و قابل اعتماد باشه.»",
      charecter: "mohammad",
      mode: "2",
      typeSpeed: 26,
      textColor: "#000000",
      bgColor: "#e0f2fe",
      bgImage: "/scenes/car/chapters/5.png",
      fontSize: 15,
      meta: null,
    },
    {
      type: "dialogue",
      text: "«من هم شاسی، چرخ‌های نرم و یدک‌کش رو طراحی می‌کنم.»",
      charecter: "sina",
      mode: "3",
      typeSpeed: 26,
      textColor: "#000000",
      bgColor: "#fef3c7",
      bgImage: "/scenes/car/chapters/5.png",
      fontSize: 15,
      meta: null,
    },
    {
      type: "task",
      text: null,
      charecter: null,
      typeSpeed: null,
      textColor: null,
      bgColor: null,
      bgImage: "/scenes/car/chapters/5.png",
      fontSize: null,
      meta: {
        id: "car-1-mission-1",
        projectId: "car-project-1",
        sceneId: "scene-5",
        order: 1,
        taskType: "mission",
        title: "پروژه ۱: ساخت ماشین یدک‌کش",
        shortDescription:
          "ساخت یک ماشین کنترلی کوچک برای کشیدن جامدادی و وسایل سبک روی زمین.",
        description:
          "کودک با کمک سه قهرمان داستان، یک ماشین کنترلی یدک‌کش می‌سازد تا وسایل سبک را در اتاق جابه‌جا کند.",
        mediaUrl: null,
        mediaText: "شروع پروژه",
        locked: false,
        dependsOn: [],
        rewardIds: [],
        validatorId: null,
        minScoreToPass: null,
        maxScore: null,
        notes: "شروع پروژه یدک‌کش پس از گفتگو درباره مشکلات اتاق.",
      },
    },
    {
      type: "task",
      text: null,
      charecter: null,
      typeSpeed: null,
      textColor: null,
      bgColor: null,
      bgImage: "/scenes/car/chapters/5.png",
      fontSize: null,
      meta: {
        id: "car-1-video-1",
        projectId: "car-project-1",
        sceneId: "scene-6",
        order: 2,
        taskType: "video",
        title: "ویدیو: مونتاژ ماشین یدک‌کش",
        shortDescription: "تماشای ویدیو آموزشی برای بستن موتور، چرخ‌ها و شاسی.",
        description:
          "کودک قدم‌به‌قدم با ویدیو پیش می‌رود تا اجزای اصلی ماشین یدک‌کش را سرهم کند.",
        mediaUrl: null,
        mediaText: "تماشای ویدیو",
        locked: false,
        dependsOn: ["car-1-mission-1"],
        rewardIds: [],
        validatorId: null,
        minScoreToPass: null,
        maxScore: null,
        notes: "مرحلهٔ مونتاژ اولیه.",
      },
    },
    {
      type: "task",
      text: null,
      charecter: null,
      typeSpeed: null,
      textColor: null,
      bgColor: null,
      bgImage: "/scenes/car/chapters/6.png",
      fontSize: null,
      meta: {
        id: "car-1-video-2",
        projectId: "car-project-1",
        sceneId: "scene-6",
        order: 3,
        taskType: "video",
        title: "ویدیو: تست نهایی و جابه‌جا کردن جامدادی",
        shortDescription: "آموزش نصب یدک‌کش و تست حرکت همراه با جامدادی.",
        description:
          "در این ویدیو کودک یاد می‌گیرد چطور یدک‌کش را وصل کند، سرعت را تنظیم کند و مسیری امن برای حرکت بسازد.",
        mediaUrl: null,
        mediaText: "پخش تست نهایی",
        locked: false,
        dependsOn: ["car-1-video-1"],
        rewardIds: [],
        validatorId: null,
        minScoreToPass: null,
        maxScore: null,
        notes: "تست نهایی قبل از ورود به بخش چالش‌ها.",
      },
    },
    {
      type: "dialogue",
      text: "«حالا وقت چالش‌هاست؛ سه بازی داریم: راه مستقیم، مسیر ترکیبی و پارک دقیق.»",
      charecter: "ravi",

      typeSpeed: 26,
      textColor: "#ffffff",
      bgColor: "#0b3b4a",
      bgImage: "/scenes/car/chapters/6.png",
      fontSize: 14,
      meta: null,
    },
    {
      type: "dialogue",
      text: "«آماده‌ای قهرمان؟ بزن بریم!»",
      charecter: "sina",
      mode: "2",
      typeSpeed: 26,
      textColor: "#000000",
      bgColor: "#fef3c7",
      bgImage: "/scenes/car/chapters/6.png",
      fontSize: 15,
      meta: null,
    },
    {
      type: "task",
      text: null,
      charecter: null,
      typeSpeed: null,
      textColor: null,
      bgColor: null,
      bgImage: "/scenes/car/chapters/6.png",
      fontSize: null,
      meta: {
        id: "car-1-challenge-1",
        projectId: "car-project-1",
        sceneId: "scene-7",
        order: 4,
        taskType: "challenge",
        title: "بازی ۱: بلوکنویسی حرکت رو به جلو",
        shortDescription:
          "عبور از زیر سه صندلی با استفاده از بلوک‌های حرکت رو به جلو بدون برخورد.",
        description:
          "کودک سه صندلی را در یک مسیر می‌چیند، یک اسباب‌بازی سبک را به یدک‌کش وصل می‌کند و با چیدن بلوک‌های «حرکت به جلو» تلاش می‌کند از زیر هر سه صندلی عبور کند.",
        mediaUrl: null,
        mediaText: "شروع بازی حرکت مستقیم",
        locked: false,
        dependsOn: ["car-1-video-2"],
        rewardIds: ["badge-straight-path"],
        validatorId: "validator-car-1-challenge-1",
        minScoreToPass: 1,
        maxScore: 3,
        notes: "هر برخورد با پایه صندلی یعنی تلاش دوباره.",
      },
    },
    {
      type: "validator",
      text: null,
      charecter: null,
      typeSpeed: null,
      textColor: null,
      bgColor: null,
      bgImage: null,
      fontSize: null,
      meta: {
        id: "validator-car-1-challenge-1",
        taskId: "car-1-challenge-1",
        states: [
          ["green-flag", "forward", "forward"],
          ["green-flag", "forward", "forward", "forward"],
          ["/^green[- ]?flag$/i", "forward", "forward"],
        ],
        blockTypes: [
          "up",
          "down",
          "delay",
          "green-flag",
          "forward",
          "backward",
          "clockwise",
          "countclockwise",
          "lamp-on",
          "lamp-off",
          "speed-low",
          "speed-high",
        ],
        notes:
          "نمونه‌هایی از دنباله بلوک‌های قابل قبول برای عبور از زیر صندلی‌ها.",
      },
    },
    {
      type: "task",
      text: null,
      charecter: null,
      typeSpeed: null,
      textColor: null,
      bgColor: null,
      bgImage: "/scenes/car/chapters/6.png",
      fontSize: null,
      meta: {
        id: "car-1-challenge-2",
        projectId: "car-project-1",
        sceneId: "scene-7",
        order: 5,
        taskType: "challenge",
        title: "بازی ۲: مسیر ترکیبی و فرمان نرم",
        shortDescription:
          "دور زدن صندلی دوم و بازگشت به زیر صندلی اول با ترکیب فرمان‌ها.",
        description:
          "کودک دو صندلی را با فاصله مناسب می‌چیند. ماشین باید از زیر صندلی اول عبور کند، دور صندلی دوم یک دور کامل بزند و دوباره به زیر صندلی اول برگردد.",
        mediaUrl: null,
        mediaText: "شروع بازی فرمان نرم",
        locked: false,
        dependsOn: ["car-1-challenge-1"],
        rewardIds: ["badge-soft-steering"],
        validatorId: null,
        minScoreToPass: 1,
        maxScore: 3,
        notes: "تمرکز روی فرمان نرم و کنترل دقیق پیچ‌ها.",
      },
    },
    {
      type: "task",
      text: null,
      charecter: null,
      typeSpeed: null,
      textColor: null,
      bgColor: null,
      bgImage: "/scenes/car/chapters/6.png",
      fontSize: null,
      meta: {
        id: "car-1-challenge-3",
        projectId: "car-project-1",
        sceneId: "scene-7",
        order: 6,
        taskType: "challenge",
        title: "بازی ۳: کنترل سرعت و پارک دقیق",
        shortDescription:
          "سه دور آرام دور صندلی و پارک نهایی زیر آن بدون برخورد.",
        description:
          "ماشین از جلوی صندلی شروع می‌کند، سه دور آرام دور صندلی می‌چرخد و در پایان زیر صندلی پارک می‌کند، بدون برخورد به پایه‌ها.",
        mediaUrl: null,
        mediaText: "شروع بازی پارک دقیق",
        locked: false,
        dependsOn: ["car-1-challenge-2"],
        rewardIds: ["badge-precise-parking"],
        validatorId: null,
        minScoreToPass: 1,
        maxScore: 3,
        notes: "کنترل سرعت و دقت در موقعیت توقف.",
      },
    },
    {
      type: "unlock",
      text: null,
      charecter: null,
      typeSpeed: null,
      textColor: null,
      bgColor: null,
      bgImage: null,
      fontSize: null,
      meta: {
        id: "unlock-badge-straight-path",
        unlockType: "badge",
        projectId: "car-project-1",
        title: "نشان مسیر مستقیم",
        description:
          "با موفقیت در بازی حرکت رو به جلو، نشان مسیر مستقیم را می‌گیری.",
        icon: "badge-straight-path",
        dependsOnRewards: [],
      },
    },
    {
      type: "unlock",
      text: null,
      charecter: null,
      typeSpeed: null,
      textColor: null,
      bgColor: null,
      bgImage: null,
      fontSize: null,
      meta: {
        id: "unlock-badge-soft-steering",
        unlockType: "badge",
        projectId: "car-project-1",
        title: "نشان فرمان نرم",
        description: "با عبور از مسیر ترکیبی، نشان فرمان نرم را می‌گیری.",
        icon: "badge-soft-steering",
        dependsOnRewards: [],
      },
    },
    {
      type: "unlock",
      text: null,
      charecter: null,
      typeSpeed: null,
      textColor: null,
      bgColor: null,
      bgImage: null,
      fontSize: null,
      meta: {
        id: "unlock-badge-precise-parking",
        unlockType: "badge",
        projectId: "car-project-1",
        title: "نشان پارک دقیق",
        description: "با پارک دقیق زیر صندلی، نشان پارک دقیق را می‌گیری.",
        icon: "badge-precise-parking",
        dependsOnRewards: [],
      },
    },
    {
      type: "unlock",
      text: null,
      charecter: null,
      typeSpeed: null,
      textColor: null,
      bgColor: null,
      bgImage: null,
      fontSize: null,
      meta: {
        id: "unlock-joystick",
        unlockType: "feature",
        projectId: "car-project-1",
        title: "باز شدن دسته کنترل",
        description:
          "با گرفتن هر سه نشان رانندگی، بخش «دسته کنترل» در اپلیکیشن باز می‌شود.",
        icon: "joystick",
        dependsOnRewards: [
          "badge-straight-path",
          "badge-soft-steering",
          "badge-precise-parking",
        ],
      },
    },
  ],
  "chapter-02": [
    {
      type: "dialogue",
      text: "«حالا نوبت مسئله‌ی دوم است؛ وقتی پیچ‌ها و مهره‌های ریز روی زمین می‌ریزند، چطور سریع و تمیز جمع‌شان کنیم؟»",
      charecter: "ravi",

      typeSpeed: 26,
      textColor: "#ffffff",
      bgColor: "#0b3b4a",
      bgImage: "/scenes/car/chapters/7.png",
      fontSize: 14,
      meta: null,
    },
    {
      type: "dialogue",
      text: "«اگر جارو بکشیم، پیچ‌ها لابه‌لای آشغال‌ها گم می‌شن.»",
      charecter: "mohammad",
      mode: "2",
      typeSpeed: 26,
      textColor: "#000000",
      bgColor: "#e0f2fe",
      bgImage: "/scenes/car/chapters/7.png",
      fontSize: 14,
      meta: null,
    },
    {
      type: "dialogue",
      text: "«اگر یک آهنربا را سر یک بازوی متحرک بگذاریم که دور اتاق بچرخد چطور؟»",
      charecter: "sina",
      mode: "3",
      typeSpeed: 26,
      textColor: "#000000",
      bgColor: "#fef3c7",
      bgImage: "/scenes/car/chapters/7.png",
      fontSize: 15,
      meta: null,
    },
    {
      type: "dialogue",
      text: "«عالیه! یک جرثقیل کنترلی کوچک با آهنربا؛ مخصوص جمع‌کردن پیچ‌ها.»",
      charecter: "arash",
      mode: "3",
      typeSpeed: 26,
      textColor: "#ffffff",
      bgColor: "#7c3aed",
      bgImage: "/scenes/car/chapters/7.png",
      fontSize: 15,
      meta: null,
    },
    {
      type: "dialogue",
      text: "«من مدار موتورها را می‌سازم، آرش برنامه‌نویسی می‌کند و سینا بازو و شاسی را طراحی می‌کند.»",
      charecter: "mohammad",
      mode: "2",
      typeSpeed: 26,
      textColor: "#000000",
      bgColor: "#e0f2fe",
      bgImage: "/scenes/car/chapters/7.png",
      fontSize: 15,
      meta: null,
    },
    {
      type: "task",
      text: null,
      charecter: null,
      typeSpeed: null,
      textColor: null,
      bgColor: null,
      bgImage: "/scenes/car/chapters/7.png",
      fontSize: null,
      meta: {
        id: "car-2-mission-1",
        projectId: "car-project-2",
        sceneId: "scene-8",
        order: 1,
        taskType: "mission",
        title: "پروژه ۲: ساخت جرثقیل آهنربایی",
        shortDescription:
          "ساخت یک جرثقیل کنترلی کوچک با آهنربا برای جمع کردن پیچ‌ها و قطعات فلزی.",
        description:
          "کودک یک سازه متحرک با بازوی ساده می‌سازد که سر آن یک آهنربای کوچک نصب شده تا پیچ‌ها را از روی زمین جمع کند.",
        mediaUrl: null,
        mediaText: "شروع پروژه",
        locked: false,
        dependsOn: [],
        rewardIds: [],
        validatorId: null,
        minScoreToPass: null,
        maxScore: null,
        notes:
          "شروع پروژه جرثقیل آهنربایی بعد از طوفان فکری درباره روش‌های جمع‌کردن پیچ‌ها.",
      },
    },
    {
      type: "task",
      text: null,
      charecter: null,
      typeSpeed: null,
      textColor: null,
      bgColor: null,
      bgImage: "/scenes/car/chapters/7.png",
      fontSize: null,
      meta: {
        id: "car-2-video-1",
        projectId: "car-project-2",
        sceneId: "scene-9",
        order: 2,
        taskType: "video",
        title: "ویدیو: مونتاژ جرثقیل آهنربایی",
        shortDescription: "آموزش بستن شاسی، بازو و نصب آهنربا روی ربات.",
        description:
          "کودک با تماشای ویدیو یاد می‌گیرد چگونه بازو، چرخ‌ها و آهنربا را طوری مونتاژ کند که بتواند پیچ‌ها را جمع کند.",
        mediaUrl: null,
        mediaText: "تماشای ویدیو",
        locked: false,
        dependsOn: ["car-2-mission-1"],
        rewardIds: [],
        validatorId: null,
        minScoreToPass: null,
        maxScore: null,
        notes: "ویدیو اصلی آموزش مونتاژ.",
      },
    },
    {
      type: "dialogue",
      text: "«آماده؟ مأموریت نجات پیچ‌های گمشده شروع شد!»",
      charecter: "sina",
      mode: "4",
      typeSpeed: 26,
      textColor: "#000000",
      bgColor: "#fef3c7",
      bgImage: "/scenes/car/chapters/7.png",
      fontSize: 15,
      meta: null,
    },
    {
      type: "dialogue",
      text: "«سرعت چرخ‌ها خوبه؛ حالا آهنربا را پایین بیاور و بعد آرام بالا ببر.»",
      charecter: "mohammad",
      mode: "2",
      typeSpeed: 26,
      textColor: "#000000",
      bgColor: "#e0f2fe",
      bgImage: "/scenes/car/chapters/7.png",
      fontSize: 15,
      meta: null,
    },
    {
      type: "task",
      text: null,
      charecter: null,
      typeSpeed: null,
      textColor: null,
      bgColor: null,
      bgImage: "/scenes/car/chapters/7.png",
      fontSize: null,
      meta: {
        id: "car-2-challenge-1",
        projectId: "car-project-2",
        sceneId: "scene-10",
        order: 3,
        taskType: "challenge",
        title: "بازی ۱: برج دستمال کاغذی",
        shortDescription:
          "برداشتن و چیدن جعبه‌های دستمال کاغذی روی هم با جرثقیل.",
        description:
          "کودک دو جعبه دستمال کاغذی را سوراخ می‌کند (با کمک بزرگ‌ترها) و با گیره جرثقیل آن‌ها را بلند می‌کند و به صورت برج روی هم می‌چیند.",
        mediaUrl: null,
        mediaText: "شروع بازی برج دستمال",
        locked: false,
        dependsOn: ["car-2-video-1"],
        rewardIds: [],
        validatorId: null,
        minScoreToPass: null,
        maxScore: null,
        notes: "تمرین تعادل و حرکت آرام جرثقیل.",
      },
    },
    {
      type: "task",
      text: null,
      charecter: null,
      typeSpeed: null,
      textColor: null,
      bgColor: null,
      bgImage: "/scenes/car/chapters/7.png",
      fontSize: null,
      meta: {
        id: "car-2-challenge-2",
        projectId: "car-project-2",
        sceneId: "scene-10",
        order: 4,
        taskType: "challenge",
        title: "بازی ۲: لیوان‌های همرنگ",
        shortDescription:
          "انتقال لیوان‌ها روی کاغذ همرنگ با استفاده از جرثقیل.",
        description:
          "کودک لیوان‌های رنگی را با گیره جرثقیل بلند می‌کند و روی کاغذ همرنگشان قرار می‌دهد؛ تمرینی برای دقت و تطبیق رنگ‌ها.",
        mediaUrl: null,
        mediaText: "شروع بازی لیوان‌های همرنگ",
        locked: false,
        dependsOn: ["car-2-challenge-1"],
        rewardIds: [],
        validatorId: null,
        minScoreToPass: null,
        maxScore: null,
        notes: "ترکیب مهارت فیزیکی و تشخیص رنگ.",
      },
    },
    {
      type: "task",
      text: null,
      charecter: null,
      typeSpeed: null,
      textColor: null,
      bgColor: null,
      bgImage: "/scenes/car/chapters/7.png",
      fontSize: null,
      meta: {
        id: "car-2-challenge-3",
        projectId: "car-project-2",
        sceneId: "scene-10",
        order: 5,
        taskType: "challenge",
        title: "بازی ۳: چیدن بار در ظرف",
        shortDescription:
          "جمع‌کردن اسباب‌بازی‌ها و قرار دادن آن‌ها در یک ظرف با جرثقیل.",
        description:
          "کودک با جرثقیل اسباب‌بازی‌های سبک را برمی‌دارد و آرام داخل ظرف می‌چیند تا فضای اتاق مرتب شود.",
        mediaUrl: null,
        mediaText: "شروع بازی چیدن بار",
        locked: false,
        dependsOn: ["car-2-challenge-2"],
        rewardIds: [],
        validatorId: null,
        minScoreToPass: null,
        maxScore: null,
        notes: "تمیزی اتاق و مدیریت فضا را تمرین می‌کند.",
      },
    },
    {
      type: "dialogue",
      text: "«دیدی؟ وقتی مسئله‌ات را به پروژه تبدیل می‌کنی، می‌توانی با یک ربات ساده، پیچ‌ها و حتی اسباب‌بازی‌ها را مرتب کنی.»",
      charecter: "ravi",

      typeSpeed: 26,
      textColor: "#ffffff",
      bgColor: "#0b3b4a",
      bgImage: "/scenes/car/chapters/7.png",
      fontSize: 14,
      meta: null,
    },
    {
      type: "dialogue",
      text: "«آفرین! امروز یک قدم دیگر دانشمندتر شدی.»",
      charecter: "ravi",

      typeSpeed: 26,
      textColor: "#ffffff",
      bgColor: "#0b3b4a",
      bgImage: "/scenes/car/chapters/7.png",
      fontSize: 14,
      meta: null,
    },
  ],
  "chapter-03": [
    {
      type: "dialogue",
      text: "«حالا می‌رسیم به مسئلهٔ توپ‌ها؛ چطور توپ‌ها را از دور به داخل سبد بندازیم؟»",
      charecter: "ravi",

      typeSpeed: 26,
      textColor: "#ffffff",
      bgColor: "#0b3b4a",
      bgImage: "/scenes/car/chapters/9.png",
      fontSize: 14,
      meta: null,
    },
    {
      type: "dialogue",
      text: "«اگر با دست پرتاب کنیم، رباتی نساختیم؛ می‌خوایم یک وسیلهٔ جدید بسازیم.»",
      charecter: "mohammad",
      mode: "2",
      typeSpeed: 26,
      textColor: "#000000",
      bgColor: "#e0f2fe",
      bgImage: "/scenes/car/chapters/9.png",
      fontSize: 14,
      meta: null,
    },
    {
      type: "dialogue",
      text: "«چطوره یک بازوی بلند با کش بسازیم که توپ را پرتاب کند؟ شبیه منجنیق!»",
      charecter: "sina",
      mode: "3",
      typeSpeed: 26,
      textColor: "#000000",
      bgColor: "#fef3c7",
      bgImage: "/scenes/car/chapters/9.png",
      fontSize: 15,
      meta: null,
    },
    {
      type: "dialogue",
      text: "«می‌تونیم این منجنیق را روی ماشین‌مان سوار کنیم و از طریق اپلیکیشن شلیک کنیم.»",
      charecter: "arash",
      mode: "3",
      typeSpeed: 26,
      textColor: "#ffffff",
      bgColor: "#7c3aed",
      bgImage: "/scenes/car/chapters/9.png",
      fontSize: 15,
      meta: null,
    },
    {
      type: "dialogue",
      text: "«نکتهٔ علمی: منجنیق از اهرم و انرژی کشسانی کمک می‌گیرد؛ زاویه و نیروی کشش روی برد پرتاب اثر دارد.»",
      charecter: "ravi",

      typeSpeed: 26,
      textColor: "#ffffff",
      bgColor: "#0b3b4a",
      bgImage: "/scenes/car/chapters/9.png",
      fontSize: 14,
      meta: null,
    },
    {
      type: "task",
      text: null,
      charecter: null,
      typeSpeed: null,
      textColor: null,
      bgColor: null,
      bgImage: "/scenes/car/chapters/8.png",
      fontSize: null,
      meta: {
        id: "car-3-mission-1",
        projectId: "car-project-3",
        sceneId: "scene-11",
        order: 1,
        taskType: "mission",
        title: "پروژه ۳: ساخت منجنیق کنترلی",
        shortDescription:
          "ساخت یک منجنیق کوچک روی ماشین برای پرتاب توپ‌های سبک به سمت سبد.",
        description:
          "کودک با اضافه کردن بازوی منجنیق به ماشین، یک سیستم پرتاب توپ می‌سازد و زاویه و کشش را تنظیم می‌کند.",
        mediaUrl: null,
        mediaText: "شروع پروژه",
        locked: false,
        dependsOn: [],
        rewardIds: [],
        validatorId: null,
        minScoreToPass: null,
        maxScore: null,
        notes: "پروژه سوم بر پایهٔ ماشین کنترلی قبلی ساخته می‌شود.",
      },
    },
    {
      type: "task",
      text: null,
      charecter: null,
      typeSpeed: null,
      textColor: null,
      bgColor: null,
      bgImage: "/scenes/car/chapters/8.png",
      fontSize: null,
      meta: {
        id: "car-3-video-1",
        projectId: "car-project-3",
        sceneId: "scene-12",
        order: 2,
        taskType: "video",
        title: "ویدیو: مونتاژ منجنیق",
        shortDescription: "آموزش ساخت بازوی منجنیق و نصب آن روی ماشین.",
        description:
          "در این ویدیو کودک با کش، بازوی پلاستیکی و نقطهٔ اتصال توپ آشنا می‌شود و آن را روی ماشین سوار می‌کند.",
        mediaUrl: null,
        mediaText: "تماشای ویدیو",
        locked: false,
        dependsOn: ["car-3-mission-1"],
        rewardIds: [],
        validatorId: null,
        minScoreToPass: null,
        maxScore: null,
        notes: "تأکید بر توپ‌های سبک و نکات ایمنی.",
      },
    },
    {
      type: "dialogue",
      text: "«آماده؟ مأموریت توپ‌های سه‌امتیازی شروع شد!»",
      charecter: "sina",
      mode: "4",
      typeSpeed: 26,
      textColor: "#000000",
      bgColor: "#fef3c7",
      bgImage: "/scenes/car/chapters/9.png",
      fontSize: 15,
      meta: null,
    },
    {
      type: "dialogue",
      text: "«سه، دو، یک... پرتاب!»",
      charecter: "arash",
      mode: "3",
      typeSpeed: 26,
      textColor: "#ffffff",
      bgColor: "#7c3aed",
      bgImage: "/scenes/car/chapters/9.png",
      fontSize: 15,
      meta: null,
    },
    {
      type: "dialogue",
      text: "«عالی! توپ‌ها با موفقیت داخل سبد افتادند.»",
      charecter: "mohammad",
      mode: "3",
      typeSpeed: 26,
      textColor: "#000000",
      bgColor: "#e0f2fe",
      bgImage: "/scenes/car/chapters/9.png",
      fontSize: 15,
      meta: null,
    },
    {
      type: "task",
      text: null,
      charecter: null,
      typeSpeed: null,
      textColor: null,
      bgColor: null,
      bgImage: "/scenes/car/chapters/9.png",
      fontSize: null,
      meta: {
        id: "car-3-challenge-1",
        projectId: "car-project-3",
        sceneId: "scene-13",
        order: 3,
        taskType: "challenge",
        title: "بازی ۱: نقطه‌زن",
        shortDescription: "پرتاب توپ به دایره‌های امتیازی روی زمین.",
        description:
          "کودک سه دایره با امتیازهای مختلف روی زمین می‌کشد و سعی می‌کند توپ را طوری پرتاب کند که در پرامتیازترین دایره فرود بیاید.",
        mediaUrl: null,
        mediaText: "شروع بازی نقطه‌زن",
        locked: false,
        dependsOn: ["car-3-video-1"],
        rewardIds: [],
        validatorId: null,
        minScoreToPass: null,
        maxScore: null,
        notes: "تنظیم زاویهٔ پرتاب و قدرت کشش.",
      },
    },
    {
      type: "task",
      text: null,
      charecter: null,
      typeSpeed: null,
      textColor: null,
      bgColor: null,
      bgImage: "/scenes/car/chapters/9.png",
      fontSize: null,
      meta: {
        id: "car-3-challenge-2",
        projectId: "car-project-3",
        sceneId: "scene-13",
        order: 4,
        taskType: "challenge",
        title: "بازی ۲: تخریب دیوار لیوانی",
        shortDescription: "چیدن هرم لیوانی و هدف‌گیری برای تخریب دیوار.",
        description:
          "کودک با لیوان‌های پلاستیکی یک هرم می‌سازد و تلاش می‌کند با پرتاب توپ به سمت آن، دیوار را کامل خراب کند.",
        mediaUrl: null,
        mediaText: "شروع بازی دیوار لیوانی",
        locked: false,
        dependsOn: ["car-3-challenge-1"],
        rewardIds: [],
        validatorId: null,
        minScoreToPass: null,
        maxScore: null,
        notes: "آزمایش نیرو و جهت، همراه با رعایت نکات ایمنی.",
      },
    },
    {
      type: "dialogue",
      text: "«قهرمان‌های لاله! یادتون باشه همهٔ بچه‌ها می‌تونن به دانشمندهای بزرگ تبدیل بشن؛ فقط کافیه سؤال بپرسن و شجاعانه دنبالش برن.»",
      charecter: "ravi",

      typeSpeed: 26,
      textColor: "#ffffff",
      bgColor: "#0b3b4a",
      bgImage: "/scenes/car/chapters/10.png",
      fontSize: 14,
      meta: null,
    },
    {
      type: "dialogue",
      text: "«هر سؤال یک راه جدیده!»",
      charecter: "arash",
      mode: "3",
      typeSpeed: 26,
      textColor: "#ffffff",
      bgColor: "#7c3aed",
      bgImage: "/scenes/car/chapters/10.png",
      fontSize: 15,
      meta: null,
    },
    {
      type: "dialogue",
      text: "«هر تلاش یک قدم رو به جلوست!»",
      charecter: "sina",
      mode: "2",
      typeSpeed: 26,
      textColor: "#000000",
      bgColor: "#fef3c7",
      bgImage: "/scenes/car/chapters/10.png",
      fontSize: 15,
      meta: null,
    },
    {
      type: "dialogue",
      text: "«هر اشتباه یک تجربهٔ تازه است!»",
      charecter: "mohammad",
      mode: "3",
      typeSpeed: 26,
      textColor: "#000000",
      bgColor: "#e0f2fe",
      bgImage: "/scenes/car/chapters/10.png",
      fontSize: 15,
      meta: null,
    },
    {
      type: "dialogue",
      text: "«حالا خبر خوب: همهٔ بخش‌های اپ باز شده و می‌تونی هرطور خواستی با برنامه‌نویسی یا با دستهٔ کنترل بازی و آزمایش‌های جدید بسازی. دنیا آزمایشگاه توست!»",
      charecter: "ravi",

      typeSpeed: 26,
      textColor: "#ffffff",
      bgColor: "#0b3b4a",
      bgImage: "/scenes/car/chapters/10.png",
      fontSize: 14,
      meta: null,
    },
    {
      type: "unlock",
      text: null,
      charecter: null,
      typeSpeed: null,
      textColor: null,
      bgColor: null,
      bgImage: null,
      fontSize: null,
      meta: {
        id: "unlock-all-sections",
        unlockType: "feature",
        projectId: "car-all-projects",
        title: "باز شدن همهٔ بخش‌ها",
        description:
          "پس از گذراندن هر سه پروژه و چالش‌هایشان، همه‌ی بخش‌های اپلیکیشن برای کودک باز می‌شود.",
        icon: "star",
        dependsOnRewards: [
          "badge-straight-path",
          "badge-soft-steering",
          "badge-precise-parking",
        ],
      },
    },
  ],
};
